# Gitlab CI/CD for guardata

.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

snap-build:
  image: kyrofa/github-snap-builder:core18
  stage: build
  timeout: 15m
  before_script:
    - cp -R packaging/snap snapbuild
    - cat CHANGELOG.rst >> README.rst
    - cd snapbuild
    - mkdir src
    - cp -R ../guardata src
    - cp ../setup.py src
    - cp ../README.rst src
  script:
    - sed -i "s#^\\(__version__ = \\).*\$#\\1'$CI_COMMIT_TAG'#" src/guardata/_version.py
    - sed -i "s/__GUARDATA_VERSION__/$CI_COMMIT_TAG/" snap/snapcraft.yaml
    - snapcraft --destructive-mode
  artifacts:
    paths:
      - snapbuild/guardata*.snap
