repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      args:
          - "--line-length=100"
          - "--target-version=py37"
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: mixed-line-ending
      args:
          - "--fix=lf"
    - id: trailing-whitespace

