repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      args:
          - "--line-length=100"
          - "--target-version=py37"
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      args:
          - "--exclude=guardata/backend/sendgrid/*"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0  # Use the ref you want to point at
    hooks:
    - id: mixed-line-ending
    - id: trailing-whitespace

