version: '2'
services:
  parsec:
    build:
      context: .
      dockerfile: packaging/docker/Dockerfile
    environment:
      - GUARDATA_HOST=0.0.0.0
      - GUARDATA_DB=postgresql://parsec@postgres/parsec?password=DBPASS  # Change db password for prod
      - GUARDATA_BLOCKSTORE=POSTGRESQL  # This is a demo...
      - GUARDATA_LOG_LEVEL=INFO
      - GUARDATA_ADMINISTRATION_TOKEN=s3cr3t  # Change for prod
      - GUARDATA_DB_FIRST_TRIES_NUMBER=20
      - GUARDATA_DB_FIRST_TRIES_SLEEP=1
    ports:
      - 6777:6777
    depends_on:
      - "postgres"
    entrypoint: []
    command: ["/bin/sh", "-c", "parsec backend migrate && parsec backend run"]

  postgres:
    image: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=parsec
      - POSTGRES_PASSWORD=DBPASS  # Change for prod
      - POSTGRES_DB=parsec


volumes:
  postgres-data:
