name: guardata
version: __GUARDATA_VERSION__
summary: trustless data cloud storage
description: |
  guardata is a secure and trustless cloud storage service,
   to share and sync your files with on-premise modern encryption.
base: core18
type: app

confinement: classic # classic is needed to have fuse working
icon: "./bin/guardata.png"
grade: stable

apps:
  guardata:
    command: guardata
    desktop: guardata.desktop
  cli:
    command: guardata-cli

parts:
  bootstrap:
    plugin: dump
    source: "./bin"
    override-pull: |
      snapcraftctl pull
      chmod 755 guardata
      chmod 755 guardata-cli

  guardata-client:
    plugin: python
    python-version: python3
    source: "./src"
    source-type: local
    override-pull: |
      snapcraftctl pull
    stage-packages:
      # fuse package contains fusermount which is sometime needed by libfuse2
      # (see: https://github.com/Scille/parsec-cloud/issues/1253)
      - fuse
      - libfuse2
      - libxext6
      - libx11-6
      - libx11-xcb1
      - libfreetype6
      - libpng16-16
      - libfontconfig
